name: Tests

on:
  pull_request:
    branches: [ main, beta ]
  push:
    branches: [ main, beta ]

jobs:
  lint:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test